[theme]
primaryColor = "#0f766e"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#171717"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
